-- [ 프로그래머스 ] 고양이와 개는 몇 마리 있을까

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS "count"
FROM ANIMAL_INS
WHERE (
    ANIMAL_TYPE = "Cat" OR
    ANIMAL_TYPE = "Dog"
)
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;


-- 아래와 같이 UNION을 사용하여 문제를 해결할 수도 있다.

SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS "count"
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = "Cat"
UNION
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) AS "count"
FROM ANIMAL_INS
WHERE ANIMAL_TYPE  = "Dog";
