-- [ 프로그래머스 ] 조건에 맞는 도서와 저자 리스트 출력하기

SELECT
    ECONOMY_BOOK.BOOK_ID,
    AUTHOR.AUTHOR_NAME,
    DATE_FORMAT(ECONOMY_BOOK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM (
    SELECT
        BOOK_ID,
        AUTHOR_ID,
        PUBLISHED_DATE
    FROM BOOK
    WHERE CATEGORY = '경제'
) AS ECONOMY_BOOK
JOIN AUTHOR
USING (AUTHOR_ID)
ORDER BY PUBLISHED_DATE ASC;
