-- [ 프로그래머스 ] 상품을 구매한 회원 비율 구하기

SELECT
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT ONLINE_SALE.USER_ID) / (SELECT SUM(YEAR(JOINED) = 2021) FROM USER_INFO),
        1
    )AS PURCHASED_RATIO
FROM USER_INFO
JOIN ONLINE_SALE
USING (USER_ID)
WHERE YEAR(USER_INFO.JOINED) = 2021
GROUP BY DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y-%m")
ORDER BY YEAR ASC, MONTH ASC;
