-- [ 프로그래머스 ] 과일로 만든 아이스크림 고르기

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
JOIN ICECREAM_INFO
USING (FLAVOR)
WHERE (
    TOTAL_ORDER >= 3000
    AND
    INGREDIENT_TYPE = "fruit_based"
)
ORDER BY TOTAL_ORDER DESC;
