-- [ 프로그래머스 ] 조건에 부합하는 중고거래 댓글 조회하기

SELECT
    TARGET_BOARD.TITLE,
    TARGET_BOARD.BOARD_ID,
    USED_GOODS_REPLY.REPLY_ID,
    USED_GOODS_REPLY.WRITER_ID,
    USED_GOODS_REPLY.CONTENTS,
    DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM (
    SELECT
        BOARD_ID,
        TITLE
    FROM USED_GOODS_BOARD
    WHERE (
        YEAR(CREATED_DATE) = 2022
        AND
        MONTH(CREATED_DATE) = 10
    )
) AS TARGET_BOARD
JOIN USED_GOODS_REPLY
USING (BOARD_ID)
ORDER BY CREATED_DATE ASC, TITLE ASC;
