-- [ 프로그래머스 ] 대여 기록이 존재하는 자동차 리스트 구하기

SELECT DISTINCT CAR_RENTAL_COMPANY_CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
USING (CAR_ID)
WHERE (
    CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '세단'
    AND
    MONTH(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE) = 10
)
ORDER BY CAR_ID DESC;
