-- [ 프로그래머스 ] 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기

SELECT
    CONCAT(CONCAT('/home/grep/src/', TARGET_BOARD.BOARD_ID), '/', CONCAT(USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT)) AS FILE_PATH
FROM (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY `VIEWS` DESC
    LIMIT 1
) AS TARGET_BOARD
JOIN USED_GOODS_FILE
USING (BOARD_ID)
ORDER BY USED_GOODS_FILE.FILE_ID DESC;
