-- [ 프로그래머스 ] 조건에 맞는 사용자와 총 거래금액 조회하기

SELECT
    USED_GOODS_USER.USER_ID,
    USED_GOODS_USER.NICKNAME,
    CONCAT_WS(' ', USED_GOODS_USER.CITY, USED_GOODS_USER.STREET_ADDRESS1, USED_GOODS_USER.STREET_ADDRESS2) AS '전체주소',
    CONCAT_WS('-', SUBSTR(USED_GOODS_USER.TLNO, 1, 3), SUBSTR(USED_GOODS_USER.TLNO, 4, 4), SUBSTR(USED_GOODS_USER.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD
JOIN USED_GOODS_USER
ON USED_GOODS_BOARD.WRITER_ID = USED_GOODS_USER.USER_ID
GROUP BY USED_GOODS_USER.USER_ID
HAVING COUNT(USED_GOODS_BOARD.BOARD_ID) >= 3
ORDER BY USER_ID DESC;
