-- [ 프로그래머스 ] 조건에 맞는 사용자 정보 조회하기

SELECT
    USED_GOODS_USER.USER_ID,
    USED_GOODS_USER.NICKNAME,
    SUM(SOLD_BOARD.PRICE) AS TOTAL_SALES
FROM (
    SELECT
        WRITER_ID AS USER_ID,
        PRICE
    FROM USED_GOODS_BOARD
    WHERE `STATUS` = 'DONE'
) AS SOLD_BOARD
JOIN USED_GOODS_USER
USING (USER_ID)
GROUP BY USED_GOODS_USER.USER_ID
HAVING SUM(SOLD_BOARD.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
