-- [ 프로그래머스 ] 오랜 기간 보호한 동물(1)

-- 유의할 점은 LIMIT 구의 처리 순서는 WHERE, ORDER 구 다음이라는 것이다.

SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE NOT EXISTS (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
)
ORDER BY DATETIME
LIMIT 3;


/*
아래와 같이 LEFT JOIN을 사용할 수 있다.
이때 ANIMAL_ID와 같이 두 테이블에 동일한 필드가 존재할 경우 `USING ()` 문법을 사용하여 간단하게 표현할 수도 있다.
*/

SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS
USING (ANIMAL_ID)
WHERE ANIMAL_OUTS IS NULL
ORDER BY DATETIME
LIMIT 3;