-- [ 프로그래머스 ] 즐겨찾기가 가장 많은 식당 정보 출력하기

SELECT
    REST_INFO.FOOD_TYPE,
    REST_INFO.REST_ID,
    REST_INFO.REST_NAME,
    FAMOUS_REST_INFO.FAVORITES
FROM (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS FAMOUS_REST_INFO
JOIN REST_INFO
USING(FOOD_TYPE, FAVORITES)
ORDER BY FOOD_TYPE DESC;
