-- [ 프로그래머스 ] 카테고리 별 도서 판매량 집계하기

SELECT
    BOOK.CATEGORY,
    SUM(SPECIFIC_BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK
JOIN (
    SELECT
        BOOK_ID,
        SALES
    FROM BOOK_SALES
    WHERE (
        YEAR(SALES_DATE) = 2022
        AND
        MONTH(SALES_DATE) = 1
    )
) AS SPECIFIC_BOOK_SALES
USING (BOOK_ID)
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ASC;
