-- [ 프로그래머스 ] 그룹별 조건에 맞는 식당 목록 출력하기

SELECT
    MEMBER_PROFILE.MEMBER_NAME,
    REST_REVIEW.REVIEW_TEXT,
    DATE_FORMAT(REST_REVIEW.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE
JOIN (
    SELECT
        MEMBER_ID,
        REVIEW_TEXT,
        REVIEW_DATE,
        COUNT(REVIEW_ID) OVER(PARTITION BY MEMBER_ID) AS REVIEW_COUNT
    FROM REST_REVIEW
) AS REST_REVIEW
USING (MEMBER_ID)
WHERE REVIEW_COUNT = (
    SELECT COUNT(REVIEW_ID) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;
