-- [ 프로그래머스 ] 저자 별 카테고리 별 매출액 집계하기

SELECT
    AUTHOR.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(BOOK.PRICE * SPECIFIC_BOOK_SALES.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK
JOIN (
    SELECT
        BOOK_ID,
        SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE (
        YEAR(SALES_DATE) = 2022
        AND
        MONTH(SALES_DATE) = 1
    )
    GROUP BY BOOK_ID
) AS SPECIFIC_BOOK_SALES
USING (BOOK_ID)
JOIN AUTHOR
USING (AUTHOR_ID)
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
