-- [ 프로그래머스 ] 5월 식품들의 총매출 조회하기

SELECT
    FOOD_PRODUCT.PRODUCT_ID,
    FOOD_PRODUCT.PRODUCT_NAME,
    SUM(FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT
JOIN FOOD_ORDER
ON (
    YEAR(FOOD_ORDER.PRODUCE_DATE) = 2022
    AND
    MONTH(FOOD_ORDER.PRODUCE_DATE) = 5
    AND
    FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
)
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
