-- [ 프로그래머스 ] 년, 월, 성별 별 상품 구매 회원 수 구하기

SELECT
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    USER_INFO.GENDER AS GENDER,
    COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM USER_INFO
JOIN ONLINE_SALE
USING (USER_ID)
WHERE USER_INFO.GENDER IS NOT NULL
GROUP BY
    DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y-%m"),
    USER_INFO.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;
