-- [ 프로그래머스 ] 취소되지 않은 진료 예약 조회하기

SELECT
    APPOINTMENT.APNT_NO,
    PATIENT.PT_NAME,
    APPOINTMENT.PT_NO,
    APPOINTMENT.MCDP_CD,
    DOCTOR.DR_NAME,
    APPOINTMENT.APNT_YMD
FROM PATIENT
JOIN APPOINTMENT
USING (PT_NO)
JOIN DOCTOR
ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID
WHERE (
    APPOINTMENT.MCDP_CD = "CS"
    AND
    DATE_FORMAT(APPOINTMENT.APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND
    APNT_CNCL_YN = "N"
)
ORDER BY APPOINTMENT.APNT_YMD ASC;
